GET http://localhost:321/api/persons

###
GET http://localhost:321/api/info

###
GET http://localhost:321/api/persons/1

###
DELETE http://localhost:321/api/persons/3

###
POST  http://localhost:321/api/persons
Content-Type: application/json

{
  "name": "Emily Medina",
  "number": "375-302-0932"
}

###
PUT  http://localhost:321/api/persons/660a099ec2f9ab84d2c648ed
Content-Type: application/json

{
  "name": "Anna Carrillo",
  "number": "375-321-0932"
}
