GET http://localhost:321/api/blogs

###
POST http://localhost:321/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTA0MWM3MzA4YTI1NDRmNzdlMTk4MCIsInVzZXJuYW1lIjoibWlkdWRldiIsImlhdCI6MTcxMjM0NTQ0OCwiZXhwIjoxNzEyNzc3NDQ4fQ.6Iy0rr-HmnI1DEiEnuQV0kFHZn_wXWvEeTrpEw_Xp80


{
  "url": "https://midu.dev/",
  "title": "Frontend, JavaScript, React, CSS, Performance",
  "author": "Miguel Angel Duran Garcia",
  "likes": 3568
}

###
DELETE http://localhost:321/api/blogs/660f3fc6b85c098844b2c25c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MGYwOTA3NzY3YWE4MDk5ZmVlYWM0NyIsInVzZXJuYW1lIjoicm9vdCIsImlhdCI6MTcxMjI3MzQ1MywiZXhwIjoxNzEyNzA1NDUzfQ.GXBeorO0keT9ybZ61fFkZsST7uEfLI16cXyYjcmih5Q

###
GET http://localhost:321/api/users

###
POST http://localhost:321/api/users
Content-Type: application/json

{
  "name": "Miguel Angel Duran Garcia",
  "username": "midudev",
  "password": "midudev"
}

###
POST http://localhost:321/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "1root3"
}