GET http://localhost:321/api/blogs

###
POST http://localhost:321/api/blogs
Content-Type: application/json

{
  "name": "Dagamblog",
  "author": "dagamdev",
  "url": "http://localhost:321/api/blogs"
}

###
GET http://localhost:321/api/users

###
POST http://localhost:321/api/users
Content-Type: application/json

{
  "username": "a",
  "password": "1reee"
}